apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.marketManInfrastructureUtilsGW.ingressName }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: infra-aks.marketman.com
    http:
      paths:
      - path: /api/utilsgateway/*
        pathType: Prefix
        backend:
          serviceName: {{ .Values.marketManInfrastructureUtilsGW.serviceName }}
          servicePort: 80